### ISSUE TITLE
ARM64 Debian Bullseye Build

### ISSUE THREAD

**Issue by luarvique** [AlexandreRouma/SDRPlusPlus#1507] opened 2024-10-31 02:40 UTC
**Feature description**
Could you please add a 64bit (arm64) Debian Bullseye build to the nightlies? Since you already build for 32bit (armhf) Bullseye, I hope it is not a lot of extra work.

**Comment by AlexandreRouma** [comment] 2024-10-31 02:44
duplicate of #1154

**Closed by AlexandreRouma** 2024-10-31 02:44 UTC
Labels: enhancement
