### ISSUE TITLE
Ultra wide upper/lower sideband

### ISSUE THREAD

**Issue by CornN64** [AlexandreRouma/SDRPlusPlus#1457] opened 2024-08-26 19:39 UTC
1st thanks for a snappy SDR program.

If at all possible it would be useful to have (for wide signals) some ultra wide mode of SSB where you can get ~24kHz bandwidth (in 48000 sps) for both upper or lower sideband as the current USB or LSB are limited to just 12kHz (or possibly just allow to extend the LP filter all the way up to 24kHz).

Cheers

**Comment by AlexandreRouma** [comment] 2024-08-26 19:51
Duplicate of #958 and #392.

**Closed by AlexandreRouma** 2024-08-26 19:51 UTC
Labels: enhancement
