### ISSUE TITLE
Manual build with linux fails

### ISSUE THREAD

**Issue by phoniclynx** [AlexandreRouma/SDRPlusPlus#1273] opened 2024-01-10 07:08 UTC
**Hardware**
- CPU: Intel i7 10gen
- RAM:32gb

**Software**
- Operating System: Linux Manjaro Wayland
- SDR++: Nightly Build (1.1.0 Oct 29 2023)

**Bug Description**
Build fails to build with error using AUR or manually with the nightly build.

Error:
```
[ 58%] Built target airspy_source
[ 59%] Built target airspyhf_source
[ 60%] Building CXX object source_modules/audio_source/CMakeFiles/audio_source.dir/src/main.cpp.o
/home/nat/SDRPlusPlus-master/source_modules/audio_source/src/main.cpp: In member function ‘void AudioSourceModule::refresh()’:
/home/nat/SDRPlusPlus-master/source_modules/audio_source/src/main.cpp:93:26: error: ‘struct RtAudio::DeviceInfo’ has no member named ‘probed’
   93 |                 if (info.probed && info.inputChannels < 2) { continue; }
      |                          ^~~~~~
make[2]: *** [source_modules/audio_source/CMakeFiles/audio_source.dir/build.make:76: source_modules/audio_source/CMakeFiles/audio_source.dir/src/main.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1562: source_modules/audio_source/CMakeFiles/audio_source.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

```

**Steps To Reproduce**
1. cmake ..
2. make -j1

**Additional info**
Unable to proceed to the next step as build fails: sh ./create_root.sh

If I do make -j4 I get more errors
```
[ 60%] Built target rigctl_client
[ 60%] Built target do_always
[ 60%] Built target scanner
/home/nat/SDRPlusPlus-master/source_modules/audio_source/src/main.cpp: In member function ‘void AudioSourceModule::refresh()’:
/home/nat/SDRPlusPlus-master/source_modules/audio_source/src/main.cpp:93:26: error: ‘struct RtAudio::DeviceInfo’ has no member named ‘probed’
   93 |                 if (info.probed && info.inputChannels < 2) { continue; }
      |                          ^~~~~~
/home/nat/SDRPlusPlus-master/sink_modules/audio_sink/src/main.cpp: In constructor ‘AudioSink::AudioSink(SinkManager::Stream*, std::string)’:
/home/nat/SDRPlusPlus-master/sink_modules/audio_sink/src/main.cpp:50:27: error: ‘struct RtAudio::DeviceInfo’ has no member named ‘probed’
   50 |                 if (!info.probed) { continue; }
      |                           ^~~~~~
/home/nat/SDRPlusPlus-master/sink_modules/audio_sink/src/main.cpp: In member function ‘bool AudioSink::doStart()’:
/home/nat/SDRPlusPlus-master/sink_modules/audio_sink/src/main.cpp:175:16: error: ‘RtAudioError’ does not name a type; did you mean ‘RtAudioErrorType’?
  175 |         catch (RtAudioError& e) {
      |                ^~~~~~~~~~~~
      |                RtAudioErrorType
make[2]: *** [source_modules/audio_source/CMakeFiles/audio_source.dir/build.make:76: source_modules/audio_source/CMakeFiles/audio_source.dir/src/main.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1562: source_modules/audio_source/CMakeFiles/audio_source.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make[2]: *** [sink_modules/audio_sink/CMakeFiles/audio_sink.dir/build.make:76: sink_modules/audio_sink/CMakeFiles/audio_sink.dir/src/main.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1886: sink_modules/audio_sink/CMakeFiles/audio_sink.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

**Comment by AlexandreRouma** [comment] 2024-01-10 07:26
duplicate of #1149

**Closed by AlexandreRouma** 2024-01-10 07:26 UTC
Labels: bug
