### ISSUE TITLE
Included rtlsdr.dll in Windows version is from 2020 and lacks V4 Dongle support

### ISSUE THREAD

**Issue by TechCom2020** [AlexandreRouma/SDRPlusPlus#1293] opened 2024-01-24 05:54 UTC
After swapping it out with the most up to date one my V4 dongle began working properly with sdr++

**Comment by AlexandreRouma** [comment] 2024-01-24 05:59
duplicate of #1170 and #1783

**Closed by AlexandreRouma** 2024-01-24 05:59 UTC
Labels: bug
