### ISSUE TITLE
Incompatible changes in rtaudio 6

### ISSUE THREAD

**Issue by meerfrau** [AlexandreRouma/SDRPlusPlus#1182] opened 2023-09-13 00:18 UTC
My distro will update to _rtaudio 6_ in a moment. So I've tried this out to find a breaking change:

**Bug Description**
```
[ 70%] Building CXX object source_modules/sdrpp_server_source/CMakeFiles/sdrpp_server_source.dir/src/main.cpp.o
./SDRPlusPlus/source_modules/audio_source/src/main.cpp: In member function 'void AudioSourceModule::refresh()':
./SDRPlusPlus/source_modules/audio_source/src/main.cpp:93:26: error: 'struct RtAudio::DeviceInfo' has no member named 'probed'
   93 |                 if (info.probed && info.inputChannels < 2) { continue; }
      |                          ^~~~~~
make[2]: *** [source_modules/audio_source/CMakeFiles/audio_source.dir/build.make:76: source_modules/audio_source/CMakeFiles/audio_source.dir/src/main.cpp.o] Error 1
```

Subsequent errors after patching:
```
./SDRPlusPlus/sink_modules/audio_sink/src/main.cpp: In constructor 'AudioSink::AudioSink(SinkManager::Stream*, std::string)':
./SDRPlusPlus/sink_modules/audio_sink/src/main.cpp:50:27: error: 'struct RtAudio::DeviceInfo' has no member named 'probed'
   50 |                 if (!info.probed) { continue; }
      |                           ^~~~~~
./SDRPlusPlus/sink_modules/audio_sink/src/main.cpp: In member function 'bool AudioSink::doStart()':
./SDRPlusPlus/sink_modules/audio_sink/src/main.cpp:175:16: error: 'RtAudioError' does not name a type; did you mean 'RtAudioErrorType'?
  175 |         catch (RtAudioError& e) {
      |                ^~~~~~~~~~~~
      |                RtAudioErrorType
```

**Comment by AlexandreRouma** [comment] 2023-09-13 00:41
Duplicate of #1149

**Closed by AlexandreRouma** 2023-09-13 00:41 UTC
Labels: bug
