### ISSUE TITLE
Crash starting with hackrf on Linux Mint

### ISSUE THREAD

**Issue by peterbmarks** [AlexandreRouma/SDRPlusPlus#1360] opened 2024-03-14 21:13 UTC
**Hardware**
- CPU: Intel Core i5-6300 @ 2.4HGz x 2
- RAM: 7.6GB
- GPU: Intel Skylake GT2 [HD Graphics 520]
- SDR: Local HackRF

**Software**
Linux Mint 21.3 Cinnamon
SDR++ v1.1.0 Built at 21:36:19, Feb 24 2024

**Bug Description**
A clear description of the bug.

SDR++ crashes when a hackrf is connected and click the start button.

**Steps To Reproduce**
1. Connect hackrf
2. Run SDR++ and select the hackrf device, the serial number is shown correctly
3. Click the start button and the program exits in a few seconds.

**Only If SDR++ fails to lauch or the SDR fails to start:**
Run SDR++ from a command line window with special parameters:
* On Linux: Open a terminal and run `sdrpp -c`
I tried -c but it isn't recognised.

marksp@latitude:~$ hackrf_info 
hackrf_info version: unknown
libhackrf version: unknown (0.6)
Found HackRF
Index: 0
Serial number: 0000000000000000a06063c82253235f
Board ID Number: 2 (HackRF One)
Firmware Version: 2018.01.1 (API:1.02)
Part ID Number: 0xa000cb3c 0x0062435a
marksp@latitude:~$ sdrpp
[15/03/2024 08:02:51.000] [INFO] SDR++ v1.1.0
[15/03/2024 08:02:51.000] [INFO] Loading config
[15/03/2024 08:02:51.000] [INFO] Using OpenGL 3.0
[15/03/2024 08:02:51.000] [INFO] Loading icons
[15/03/2024 08:02:51.000] [INFO] Loading band plans
[15/03/2024 08:02:51.000] [INFO] Loading band plans color table
[15/03/2024 08:02:51.000] [INFO] Loading modules
[15/03/2024 08:02:51.000] [INFO] Loading /usr/lib/sdrpp/plugins/iq_exporter.so
[15/03/2024 08:02:51.000] [INFO] Loading /usr/lib/sdrpp/plugins/audio_sink.so
[15/03/2024 08:02:51.000] [INFO] Loading /usr/lib/sdrpp/plugins/sdrpp_server_source.so
[15/03/2024 08:02:51.000] [INFO] Loading /usr/lib/sdrpp/plugins/pager_decoder.so
[15/03/2024 08:02:51.000] [INFO] Loading /usr/lib/sdrpp/plugins/limesdr_source.so
[15/03/2024 08:02:51.000] [ERROR] Couldn't load /usr/lib/sdrpp/plugins/limesdr_source.so: libLimeSuite.so.20.10-1: cannot open shared object file: No such file or directory
[15/03/2024 08:02:51.000] [INFO] Loading /usr/lib/sdrpp/plugins/spectran_http_source.so
[15/03/2024 08:02:51.000] [INFO] Loading /usr/lib/sdrpp/plugins/recorder.so
[15/03/2024 08:02:51.000] [INFO] Loading /usr/lib/sdrpp/plugins/discord_integration.so
[15/03/2024 08:02:51.000] [INFO] Loading /usr/lib/sdrpp/plugins/frequency_manager.so
[15/03/2024 08:02:51.000] [INFO] Loading /usr/lib/sdrpp/plugins/new_portaudio_sink.so
[15/03/2024 08:02:51.000] [INFO] Loading /usr/lib/sdrpp/plugins/rigctl_client.so
[15/03/2024 08:02:51.000] [INFO] Loading /usr/lib/sdrpp/plugins/radio.so
[15/03/2024 08:02:51.000] [INFO] Loading /usr/lib/sdrpp/plugins/rfspace_source.so
[15/03/2024 08:02:51.000] [INFO] Loading /usr/lib/sdrpp/plugins/airspy_source.so
[15/03/2024 08:02:51.000] [INFO] Loading /usr/lib/sdrpp/plugins/soapy_source.so
[15/03/2024 08:02:51.000] [INFO] Loading /usr/lib/sdrpp/plugins/m17_decoder.so
[15/03/2024 08:02:51.000] [INFO] Loading /usr/lib/sdrpp/plugins/sdrplay_source.so
[15/03/2024 08:02:51.000] [INFO] Loading /usr/lib/sdrpp/plugins/perseus_source.so
[15/03/2024 08:02:51.000] [ERROR] Couldn't load /usr/lib/sdrpp/plugins/perseus_source.so: libperseus-sdr.so.0: cannot open shared object file: No such file or directory
[15/03/2024 08:02:51.000] [INFO] Loading /usr/lib/sdrpp/plugins/spyserver_source.so
[15/03/2024 08:02:51.000] [INFO] Loading /usr/lib/sdrpp/plugins/hackrf_source.so
[15/03/2024 08:02:51.000] [INFO] Loading /usr/lib/sdrpp/plugins/rtl_tcp_source.so
[15/03/2024 08:02:51.000] [INFO] Loading /usr/lib/sdrpp/plugins/network_source.so
[15/03/2024 08:02:51.000] [INFO] Loading /usr/lib/sdrpp/plugins/airspyhf_source.so
[15/03/2024 08:02:51.000] [INFO] Loading /usr/lib/sdrpp/plugins/rtl_sdr_source.so
[15/03/2024 08:02:51.000] [INFO] Loading /usr/lib/sdrpp/plugins/bladerf_source.so
[15/03/2024 08:02:51.000] [INFO] Loading /usr/lib/sdrpp/plugins/rigctl_server.so
[15/03/2024 08:02:51.000] [INFO] Loading /usr/lib/sdrpp/plugins/scanner.so
[15/03/2024 08:02:51.000] [INFO] Loading /usr/lib/sdrpp/plugins/hermes_source.so
[15/03/2024 08:02:51.000] [INFO] Loading /usr/lib/sdrpp/plugins/meteor_demodulator.so
[15/03/2024 08:02:51.000] [INFO] Loading /usr/lib/sdrpp/plugins/network_sink.so
[15/03/2024 08:02:51.000] [INFO] Loading /usr/lib/sdrpp/plugins/audio_source.so
[15/03/2024 08:02:51.000] [INFO] Loading /usr/lib/sdrpp/plugins/plutosdr_source.so
[15/03/2024 08:02:51.000] [INFO] Loading /usr/lib/sdrpp/plugins/file_source.so
[15/03/2024 08:02:51.000] [INFO] Initializing Airspy Source (airspy_source)
[15/03/2024 08:02:51.000] [INFO] Initializing AirspyHF+ Source (airspyhf_source)
[15/03/2024 08:02:51.000] [INFO] Initializing Audio Sink (audio_sink)
[15/03/2024 08:02:51.000] [INFO] Initializing Audio Source (audio_source)
[15/03/2024 08:02:51.000] [INFO] New DSP samplerate: 44100.000000 (source samplerate is 44100.000000)
[15/03/2024 08:02:51.000] [INFO] Initializing BladeRF Source (bladerf_source)
[15/03/2024 08:02:51.000] [ERROR] Could not list devices -7
[15/03/2024 08:02:51.000] [INFO] Initializing File Source (file_source)
[15/03/2024 08:02:51.000] [INFO] Initializing Frequency Manager (frequency_manager)
[15/03/2024 08:02:51.000] [INFO] Initializing HackRF Source (hackrf_source)
[15/03/2024 08:02:51.000] [INFO] Initializing Hermes Source (hermes_source)
[15/03/2024 08:02:51.000] [INFO] Initializing LimeSDR Source (limesdr_source)
[15/03/2024 08:02:51.000] [ERROR] Module 'limesdr_source' doesn't exist
[15/03/2024 08:02:51.000] [INFO] Initializing Network Sink (network_sink)
[15/03/2024 08:02:51.000] [INFO] Initializing PlutoSDR Source (plutosdr_source)
[15/03/2024 08:02:52.000] [INFO] Initializing RFspace Source (rfspace_source)
[15/03/2024 08:02:52.000] [INFO] Initializing RTL-SDR Source (rtl_sdr_source)
[15/03/2024 08:02:52.000] [INFO] Initializing RTL-TCP Source (rtl_tcp_source)
[15/03/2024 08:02:52.000] [INFO] Initializing Radio (radio)
[Resamp] predec: 8192, interp: 2000, decim: 441, inacc: 0.000000%, taps: 152000
[Resamp] predec: 4, interp: 96, decim: 125, inacc: 0.000000%, taps: 9500
[Resamp] predec: 1, interp: 80, decim: 147, inacc: 0.000000%, taps: 11172
[Resamp] predec: -2147483648, interp: 2, decim: 1, inacc: 0.000000%, taps: 152
[Resamp] predec: -2147483648, interp: 147, decim: 80, inacc: 0.000000%, taps: 11172
[15/03/2024 08:02:52.000] [WARN] Demod switch took 2852 us
[15/03/2024 08:02:53.000] [INFO] RtAudio stream open
[15/03/2024 08:02:53.000] [INFO] Initializing Recorder (recorder)
[15/03/2024 08:02:53.000] [INFO] Initializing Rigctl Server (rigctl_server)
[15/03/2024 08:02:53.000] [INFO] Initializing SDR++ Server Source (sdrpp_server_source)
[15/03/2024 08:02:53.000] [INFO] Initializing SDRplay Source (sdrplay_source)
[15/03/2024 08:02:53.000] [INFO] Initializing SoapySDR Source (soapy_source)
[INFO] [UHD] linux; GNU C++ version 11.2.0; Boost_107400; UHD_4.1.0.5-3
[15/03/2024 08:02:53.000] [INFO] Setting sample rate to 8000.000000
[Resamp] predec: 8192, interp: 3, decim: 1, inacc: 0.000000%, taps: 228
[15/03/2024 08:02:53.000] [INFO] New DSP samplerate: 8000.000000 (source samplerate is 8000.000000)
[15/03/2024 08:02:53.000] [INFO] Initializing SpyServer Source (spyserver_source)
[15/03/2024 08:02:53.000] [INFO] Loading color maps
[15/03/2024 08:02:53.000] [INFO] Loading /usr/share/sdrpp/colormaps/vivid.json
[15/03/2024 08:02:53.000] [INFO] Loading /usr/share/sdrpp/colormaps/smoke.json
[15/03/2024 08:02:53.000] [INFO] Loading /usr/share/sdrpp/colormaps/greyscale.json
[15/03/2024 08:02:53.000] [INFO] Loading /usr/share/sdrpp/colormaps/plasma.json
[15/03/2024 08:02:53.000] [INFO] Loading /usr/share/sdrpp/colormaps/websdr.json
[15/03/2024 08:02:53.000] [INFO] Loading /usr/share/sdrpp/colormaps/viridis.json
[15/03/2024 08:02:53.000] [INFO] Loading /usr/share/sdrpp/colormaps/electric.json
[15/03/2024 08:02:53.000] [INFO] Loading /usr/share/sdrpp/colormaps/gqrx.json
[15/03/2024 08:02:53.000] [INFO] Loading /usr/share/sdrpp/colormaps/classic.json
[15/03/2024 08:02:53.000] [INFO] Loading /usr/share/sdrpp/colormaps/inferno.json
[15/03/2024 08:02:53.000] [INFO] Loading /usr/share/sdrpp/colormaps/turbo.json
[15/03/2024 08:02:53.000] [INFO] Loading /usr/share/sdrpp/colormaps/temper_colors.json
[15/03/2024 08:02:53.000] [INFO] Loading /usr/share/sdrpp/colormaps/classic_green.json
[15/03/2024 08:02:53.000] [INFO] Loading /usr/share/sdrpp/colormaps/magma.json
[Resamp] predec: 128, interp: 96, decim: 125, inacc: 0.000000%, taps: 9500
[15/03/2024 08:02:53.000] [INFO] New DSP samplerate: 4000000.000000 (source samplerate is 4000000.000000)
[15/03/2024 08:02:53.000] [INFO] HackRFSourceModule 'HackRF Source': Menu Select!
[Resamp] predec: 128, interp: 96, decim: 125, inacc: 0.000000%, taps: 9500
[Resamp] predec: 128, interp: 96, decim: 125, inacc: 0.000000%, taps: 9500
[15/03/2024 08:02:53.000] [INFO] New DSP samplerate: 4000000.000000 (source samplerate is 4000000.000000)
[Resamp] predec: -2147483648, interp: 147, decim: 80, inacc: 0.000000%, taps: 11172
[15/03/2024 08:02:53.000] [INFO] RtAudio stream open
[15/03/2024 08:02:53.000] [INFO] HackRFSourceModule 'HackRF Source': Tune: 7108500.352931!
[15/03/2024 08:02:53.000] [INFO] Running post-init for Airspy Source
[15/03/2024 08:02:53.000] [INFO] Running post-init for AirspyHF+ Source
[15/03/2024 08:02:53.000] [INFO] Running post-init for Audio Sink
[15/03/2024 08:02:53.000] [INFO] Running post-init for Audio Source
[15/03/2024 08:02:53.000] [INFO] Running post-init for BladeRF Source
[15/03/2024 08:02:53.000] [INFO] Running post-init for File Source
[15/03/2024 08:02:53.000] [INFO] Running post-init for Frequency Manager
[15/03/2024 08:02:53.000] [INFO] Running post-init for HackRF Source
[15/03/2024 08:02:53.000] [INFO] Running post-init for Hermes Source
[15/03/2024 08:02:53.000] [INFO] Running post-init for Network Sink
[15/03/2024 08:02:53.000] [INFO] Running post-init for PlutoSDR Source
[15/03/2024 08:02:53.000] [INFO] Running post-init for RFspace Source
[15/03/2024 08:02:53.000] [INFO] Running post-init for RTL-SDR Source
[15/03/2024 08:02:53.000] [INFO] Running post-init for RTL-TCP Source
[15/03/2024 08:02:53.000] [INFO] Running post-init for Radio
[15/03/2024 08:02:53.000] [INFO] Running post-init for Recorder
[15/03/2024 08:02:53.000] [INFO] Running post-init for Rigctl Server
[15/03/2024 08:02:53.000] [INFO] Running post-init for SDR++ Server Source
[15/03/2024 08:02:53.000] [INFO] Running post-init for SDRplay Source
[15/03/2024 08:02:53.000] [INFO] Running post-init for SoapySDR Source
[15/03/2024 08:02:53.000] [INFO] Running post-init for SpyServer Source
[15/03/2024 08:02:53.000] [INFO] Ready.
Segmentation fault (core dumped)
marksp@latitude:~$ 

**Screenshots**
Add any screenshot that is relevant to the bug (GUI error messages, strange behavior, graphics glitch, etc...).

**Additional info**
I don't know when this started.

Thank you for a wonderful program!

**Comment by AlexandreRouma** [comment] 2024-03-14 21:30
duplicate of #337 #488 #760 #819 #1072 (and many others...). It's a conflict caused by libhackrf not checking if it's already inialized. There is **nothing** I can do about it.

The solution has been in the readme since almost day 1 of the project, please search existing issues and have a look at the documentation before opening an issue.
![image](https://github.com/AlexandreRouma/SDRPlusPlus/assets/17126412/c1208167-7f77-482b-ad40-ed1c2daf22aa)

**Closed by AlexandreRouma** 2024-03-14 21:30 UTC
Labels: bug

**Comment by peterbmarks** [comment] 2024-03-14 21:37
I'm very sorry to waste your time. I did search for any **open** bugs about HackRF but found none. Perhaps you should leave 1 open bug? (I realise it's not your bug).
