### ISSUE TITLE
List of interface suggestions

### ISSUE THREAD

**Issue by fragilepantsu** [AlexandreRouma/SDRPlusPlus#976] opened 2023-01-29 08:19 UTC
Hi!

I'm using the Windows version. Would like you to consider adding some things to the interface:

1. When creating a record in Frequency Manager, the name of the next record should be the same as the previous one created. This will reduce the time of typing in the Name field if the same type of signals are added to the favorites. 

2. Add possibility to adjust FFT Zoom, Max, Min sliders by mouse wheel while hovering. 

3. Possibility to zoom FFT with mouse wheel. Now it works like moving VFO. But for example with shift or ctrl pressed it would be possible to change zoom.

**Comment by AlexandreRouma** [comment] 2023-01-29 16:23
1. I don't think that's a good idea. keeping a state like that could make many users think they're editing an existing bookmark.
2. Duplicate of https://github.com/AlexandreRouma/SDRPlusPlus/issues/667
3. Those keybinds are already used up and it wouldn't make much sense since it would set up the expectation that the zoom will occur at the cursor when the zoom should always happen around the VFO.

**Closed** 2024-08-15 07:42 UTC
Labels: enhancement
