### ISSUE TITLE
AppImage or tarball releases for Linux

### ISSUE THREAD

**Issue by smahdink** [AlexandreRouma/SDRPlusPlus#1283] opened 2024-01-20 11:35 UTC
Currently, this project only ships debian packages, so the users of other distros must compile the program from source to run it, and it's a hassle.
It would be great to ship Linux builds as AppImages or tarballs so that everyone can enjoy using this software.

**Comment by AlexandreRouma** [comment] 2024-01-20 13:33
Duplicate of https://github.com/AlexandreRouma/SDRPlusPlus/issues/286

**Closed by AlexandreRouma** 2024-01-20 13:33 UTC
Labels: enhancement
