### ISSUE TITLE
dsp/pll.h and pll/demodulator.h is missing from the Master Branch.  

### ISSUE THREAD

**Issue by jerrynsr** [AlexandreRouma/SDRPlusPlus#1321] opened 2024-02-06 21:03 UTC
I am attempting the build all the plugins for AARCH64.   I checked in a .deb package into my fork minus some plugins because I pll/dsp.h and pll/demodulator.h are missing.  Specifically I would really like to use the SSTV and Wefax plugins.  I would like to also port some plugins over, but at this moment I can't.  

Here's the location of my fork. 
https://github.com/jerrynsr/SDRPlusPlus/tree/patch-1

Thanks

**Comment by AlexandreRouma** [comment] 2024-02-07 14:31
Duplicate of #1093

**Closed by AlexandreRouma** 2024-02-07 14:31 UTC
Labels: enhancement
