### ISSUE TITLE
AppImage release

### ISSUE THREAD

**Issue by Miki994** [AlexandreRouma/SDRPlusPlus#769] opened 2022-05-27 14:23 UTC
Can you please make AppImage release for SDR++ ? 
Currently i am using Void Linux distro and xbps package is not available.
The best and convenient way to run SDR ++ on other distros will be AppImage (portable app)
This will help also with less packages to be downloaded and make distro slim and bloat-free.

**Comment by AlexandreRouma** [comment] 2022-05-27 17:14
Duplicate of #286

Support for AppImage is not planned.

**Closed by AlexandreRouma** 2022-05-27 17:14 UTC
