### ISSUE TITLE
Latest nightly build doesn't work with RSP1A

### ISSUE THREAD

**Issue by delboy85341** [AlexandreRouma/SDRPlusPlus#1318] opened 2024-02-03 05:54 UTC
# WARNING: Filling out the template below is NOT optional. Issues not filling out this template will be closed without review.

FIRST: Before reporting any bug, make sure that the bug you are reporting has not been reported before. Also, try to use the [nightly version](https://www.sdrpp.org/nightly) if possible in case I've already fixed the bug.

**Hardware**
- CPU:  Intel(R) Core(TM) i5-3570 CPU @ 3.40GHz
- RAM: 32GB
- GPU: NVIDIA Corporation GK208B [GeForce GT 710]
- SDR: SDR Play RSP1A
**Software**
- Operating System: Name Ubuntu 22.04.3 LTS
- SDR++: v1.1.0 build at 00:45:36 February 3 2024

**Bug Description**
I installed the latest nightly build. I started Sdrpp but it didn't detect my SDR (SDRPlay RSP1A).

**Steps To Reproduce**
1. install nightly build v1.1.0 build at 00:45:36 February 3 2024
2. Launch the program
3. Click the arrow under Source.  The RSP1A isn't listed.

**Only If SDR++ fails to lauch or the SDR fails to start:**
* On Linux: Open a terminal and run `sdrpp -c`

Then, post the **entire** logs from start to after the issue. **DOT NOT truncate to where you *think* the error is...**
delboy@ladmo:~$ sdrpp -c
[02/02/2024 22:47:10.000] [INFO] SDR++ v1.1.0
Unknown argument
-a --addr               Server mode address
   --autostart          Automatically start the SDR after loading
-h --help               Show help
-p --port               Server mode port
-r --root               Root directory, where all config files are stored
-s --server             Run in server mode
delboy@ladmo:~$ 

**Screenshots**
Add any screenshot that is relevant to the bug (GUI error messages, strange behavior, graphics glitch, etc...).
![Screenshot_20240126_234008](https://github.com/AlexandreRouma/SDRPlusPlus/assets/102181740/2eaed711-9cc7-4b69-b5f7-961243a7efb4)
![Screenshot_20240202_224838](https://github.com/AlexandreRouma/SDRPlusPlus/assets/102181740/180e6c1f-5041-4a7a-b074-476ea20ed3ff)
![Screenshot_20240202_224922](https://github.com/AlexandreRouma/SDRPlusPlus/assets/102181740/b00efdbd-62e2-4696-b460-275d1d0b0b11)

**Additional info**
Add any other relevant information.

I reinstalled the nightly build from October 19 2023.  It works.

**Comment by AlexandreRouma** [comment] 2024-02-03 13:06
Duplicate of #1300

**Closed by AlexandreRouma** 2024-02-03 13:06 UTC
Labels: bug
