### ISSUE TITLE
Software crashes if startup with showWaterfall set false

### ISSUE THREAD

**Issue by JoNoci** [AlexandreRouma/SDRPlusPlus#61] opened 2021-01-10 12:20 UTC
SDR++ v0.2.5_beta (Dec 24 2020). If I execute this software, disable view of the waterfall, and exit - thereafter the software 'crashes' when I try execute it again. The only way to get it to execute again is to manually edit the config.json to set showWaterfall to true. Hence it appears that the software has a problem if it is started with showWaterfall set false.

**Comment by AlexandreRouma** [comment] 2021-01-10 16:21
Hi

I'm not able to reproduce this on windows, what OS are you using?

**Comment by nmaster2042** [comment] 2021-01-10 16:51
Hi, tried this on ubuntu, sdrpp built from sources, no issue.

**Comment by dd5fz** [comment] 2021-01-10 18:04
This may well be the reason why my test on a Raspberry Pi 4 is now crashing (issue #62).

**Comment by JoNoci** [comment] 2021-01-10 18:30
I am using Windows 10. I get the problem with both the build I downloaded
as a pre-built build and also if I recompile the code myself. Note that the
'crash' only happens when you start the SDR using the START button top left
- ie the code starts executing, I see just the window for the FFT display
is allocated - then START --> then it crashes

**Comment by AlexandreRouma** [comment] 2021-01-10 21:24
> Note that the
'crash' only happens when you start the SDR using the START button top left. - ie the code starts executing, I see just the window for the FFT display
is allocated - then START --> then it crashes

I See, this is an important detail
I'll try to repro this in a minute

**Comment by AlexandreRouma** [comment] 2021-01-10 21:48
Can repro the bug, I think I know where the issue is

**Comment by AlexandreRouma** [comment] 2021-01-11 02:19
The bug should be fixed.
Could you pull and build the latest commit to confirm?

**Comment by JoNoci** [comment] 2021-01-11 12:08
Many thanks - it is sorted.
Joe

**Closed** 2021-01-11 12:21 UTC
Labels: bug, help wanted
