### ISSUE TITLE
No Throttle from File Source to Network Sink

### ISSUE THREAD

**Issue by MichealShoemaker** [AlexandreRouma/SDRPlusPlus#1210] opened 2023-10-16 19:24 UTC
**Hardware**
- CPU: Intel Core i7-12700H
- RAM: 32.0 GB
- GPU: NVIDIA RTX A1000 Laptop
- SDR: File Source

**Software**
- Operating System: Ubuntu 20.04
- SDR++: v1.1.0 (Built at 11:39:13, Sep 27 2023)

**Bug Description**
When using a File Source with a network sink, there is nothing the throttle the data.  So, the data is read and sent out of the socket as fast as SDR++ can. 
When using UDP, this would make any listening process that processes the data to drop a significant amount of data.
When using TCP, this is less of an issue because the data (and waterfall) will pause while waiting for an ACK on the current data packet.

**Steps To Reproduce**
1. Load a wave file in the File Source
2. Use the sink module and press "Start" and the status should read "Listening" (TCP or "Sending" (UDP)
3. Press the Play button to start SDR++
4. Connect to the server/port on an external application
5. Then, the external application will either be missing data (UDP) or the waterfall in SDR++ will play/freeze (TCP)

**Comment by AlexandreRouma** [comment] 2023-10-16 19:40
Duplicate of #688, not a bug

**Closed by AlexandreRouma** 2023-10-16 19:40 UTC
Labels: bug
