### ISSUE TITLE
Allow Left and Right Channel for Audio

### ISSUE THREAD

**Issue by grahampaull** [AlexandreRouma/SDRPlusPlus#1231] opened 2023-11-17 14:26 UTC
The ability to select which speaker a VFO plays through.

I currently listen to 2 VFOs but would like to set an Audio Sink to play through the Left Speaker/Channel and another Audio Sink to play through the Right Speaker/Channel.

I also use VoxCall which allows me to feed audio to my rdio-scanner app, it allows to feed stereo, left or right. 

This works well using the the AUX-VFO plugin on SDR#:
![image](https://github.com/AlexandreRouma/SDRPlusPlus/assets/26274989/541cb76e-5d57-4592-9dfb-3dcd1466c881)

**Comment by grahampaull** [comment] 2023-11-19 17:10
> Already implemented in the `new_sinks` branch but it's not currently usable. Will notify when merged back.

Excellent! Thank you.

**Comment by AlexandreRouma** [comment] 2024-02-15 21:38
Just realized this is a duplicate of #653, follow that issue instead

**Closed by AlexandreRouma** 2024-02-15 21:38 UTC
Labels: enhancement
