### ISSUE TITLE
Mac OSX ARM not working with SDRPLAY

### ISSUE THREAD

**Issue by K4MLB** [AlexandreRouma/SDRPlusPlus#1464] opened 2024-09-03 12:50 UTC
Hardware

    CPU: Apple M1 
    RAM: 8 GB
    GPU: Apple M1 
    SDR: RSPDX

Software

    Operating System: MacOS 14.5 
    SDR++: v1.2.0 (Built at 22:34:19 Aug 19 2024)
    Bug Description
    SDR Play is unavailable.

sdr++ arm does not show sdrplay in the source drop down, nor does it show in the module manager.

ln -s /usr/local/lib/libsdrplay_api.so.3 /Applications/SDR++.app/Contents/Frameworks 

returns "File exists" but the issue remains. (issue 1431)

Mac Intel seems to work normally?

**Comment by AlexandreRouma** [comment] 2024-09-04 15:49
duplicate of #1431, follow that one instead.

**Closed by AlexandreRouma** 2024-09-04 15:49 UTC
Labels: bug

**Comment by AlexandreRouma** [comment] 2024-09-04 16:09
The 1431 issue is not marked as solve. There is no reason to open another one for the same issue.
The "fix" was something the user who submitted the bug request suggested, not something I did.
