### ISSUE TITLE
sdrpp crash at loading while youtube is playing in the background

### ISSUE THREAD

**Issue by Skav** [AlexandreRouma/SDRPlusPlus#912] opened 2022-11-09 19:22 UTC
**Hardware**
- CPU:  Xeon 1230v3
- RAM: 16GB ddr3
- GPU: RX6600
- SDR: Local

**Software**
- Operating System: Pop_OS 22.04
- SDR++:  nightly v1.1.0 Build: Oct 19 2022

**Bug Description**
Sometimes SDR++ crashesh at "Loading inferno.json" file while firefox with youtube is working in the background.
**Steps To Reproduce**
1. Lanunch firefox and go to youtube
2. Choose any video/live and start watch it (video must be playing in the background, when it's stopped it will probably work)
3. Try to turn on SDR++, it will probably crash at startup

**Only If SDR++ fails to lauch or the SDR fails to start:**
So, sdr tells me "-c" parameter is unknown, but when i try launch it from console i have this message

RtApiCore::callbackEvent(): the JACK buffer size has changed ... cannot process!

**Screenshots**
![image](https://user-images.githubusercontent.com/33636668/200921135-616d02f1-4be7-48ec-963d-07ce37ff5865.png)

**Additional info**
- This problem seems to not occure chromium browser, i don't know it is because it work on diffrent engine, or because i almost don't have any extensions on it

**Comment by ericek111** [comment] 2022-11-10 11:04
Duplicate of https://github.com/AlexandreRouma/SDRPlusPlus/issues/618

Run `export PIPEWIRE_NOJACK=1` befure starting SDR++.

**Closed** 2022-11-14 16:00 UTC
Labels: bug
