### ISSUE TITLE
RTL-SDR.Com V4 dll ?

### ISSUE THREAD

**Issue by Hackrfan** [AlexandreRouma/SDRPlusPlus#1407] opened 2024-05-25 07:42 UTC
RTL SDR.Com Stick Version 4: Please replace rtlsdr.dll with the latest driver version for version 4. 
Currently no function with the old driver under Win 7

**Comment by AlexandreRouma** [comment] 2024-05-26 19:46
Not a bug and duplicate of #1388, follow that one instead.

**Closed by AlexandreRouma** 2024-05-26 19:46 UTC
Labels: bug
