### ISSUE TITLE
Does frequency manager support Chinese?

### ISSUE THREAD

**Issue by wyz0330** [AlexandreRouma/SDRPlusPlus#901] opened 2022-10-27 04:32 UTC
**Feature description**
Does frequency manager support Chinese? 
Now the Chinese characters were garbled
![image](https://user-images.githubusercontent.com/41727378/198191968-b670708e-2c9c-4eb3-933d-2e0a728be15f.png)

**Comment by AlexandreRouma** [comment] 2022-10-27 11:51
Duplicate of https://github.com/AlexandreRouma/SDRPlusPlus/issues/701
Will not be supported.

**Closed by AlexandreRouma** 2022-10-27 11:51 UTC
Labels: enhancement
