### ISSUE TITLE
Is Android TV Box as a remote server possible?

### ISSUE THREAD

**Issue by RednazPublic** [AlexandreRouma/SDRPlusPlus#1286] opened 2024-01-21 19:36 UTC
Alexandre,

Thank you for your commitment and dedication to SDRPP.
I received as a gift an Android TV Box (HD MX10) with Android version 13 but it doesn't run Opengl 2.1. So I thought about using as a remote server for a Raspberry pi 4B. I installed SDRPP on Android TV, I installed a terminal app and I'm rooted, but I can't find where is the correct SDRPP app to start the server.

I tested with the command “sdrpp --server” in all the folders I found but it didn’t work.

1) Is it possible to run a remote server on an Android TV Box?
2) If you can help me, in which folder is the app to run as a remote server? Or if you have any tips for locating the folder.

Thanks
Rednaz

**Comment by AlexandreRouma** [comment] 2024-01-21 19:37
Duplicate of https://github.com/AlexandreRouma/SDRPlusPlus/issues/1276

**Closed by AlexandreRouma** 2024-01-21 19:37 UTC
